student service, model and routes
sodiqyekeen/dev-thrive24 pull request #7
Opened 2024-01-12 10:14 UTC by GodsAMBASSADOR

2024-01-15 19:06 UTC, sodiqyekeen requested changes

2024-01-15 19:06 UTC, sodiqyekeen commented on skillbridge/services/student_service.py
> +CREATE TABLE student (
Why is this here?

2024-01-16 11:18 UTC, GodsAMBASSADOR commented on skillbridge/services/student_service.py
> +CREATE TABLE student (
I used it to guide myself in creating the functions sir. I forgot to delete it i guess

2024-01-16 15:48 UTC, sodiqyekeen approved these changes

2024-01-16 15:48 UTC, merged